config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user
  get 'packback/new'
root 'packback#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/packback_controller.rb
class PackbackController < ApplicationController

	def index
	end
	
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packback_helper.rb
module PackbackHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Packback</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/packback/index.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>Home</title>
	<meta charset="UTF-8">
</head>
<body>

<div class='logo'> <a href=<%=root_path%>><%= image_tag "Logo.svg",  alt:"Packback Logo"%></a> </div>
<div id="case-study">
Packback Case Study
</div>
<div id='Body'> <%= image_tag "Body.svg", alt:"Packback Case Study image"%> </div>
<div id='Body2'> 
	<p id="header">Packback Questions Improves<br>
	    Student Engagement & Retention </p>
	<p id="header2">Case Study #12: Professor Smith, Illinois State University, 2017 </p>
	<p id="csbody">
	Jodi utilized Packback Answers in both of her courses this semester;
	Communication Theory and Introduction to Mass Communication.
	Both of these courses had approximately 150 students per class, and
	catered to the Freshman/Sophomore communication or general
	education student. Her goal in using Packback was to finally use a
	discussion board that cultivated quality discussion rather than just
	being busy work.	<%= image_tag "mascot.svg", alt:"Mascot image"%>
	</p>
	<p class="blue-header">
	“Packback completely changed the way my class interacted
	</p>
	<p class="blue-header">
	and engaged with the material. They became truly curious.”
	</p>
</div>


<div id="mirror-panel">
	<div id=mirror>
		<p class="mirror-header">
		What has your experience been with Packback?
		</p>
		<p class="mirror-paragraph">
		<strong class="mirror-author">Professor Smith:</strong>“Before Packback I wasn’t able
		to effectively manage participation and
		discussion in my lecture halls. It’s difficult tor
		manage a meaningful discussion in a room with
		100 people, and I knew there were a lot of kids
		not participating. I knew they had important
		contributions to make, too! I had tried
		discussion boards on our LMS (Sakai) without a
		great deal of success. Eventually, I just gave up.”
		</p>
	</div>

	<div id=mirror2>
		<p class="mirror-header">
			How did you previously manage discussion?
		</p>
		
		<p class="mirror-paragraph">
		<strong class="mirror-author">Professor Smith:</strong>“Packback has exceeded my
		expectations in every way. It’s intuitive for the
		students to use and it’s easy to peruse and
		participate in discussions…[and] hasn’t added to
		my workload, which I appreciate. What has
		surprised me the most are the quality of the
		questions the students are submitting. The
		students ask questions that move far beyond
		simple knowledge and comprehension of course.
		</p>
	</div>
</div>
<div id='stats'>
<p>Overall Stats and outcomes from Professor Smith’s Course</p>
<p id="numbers">2000 5700 400 30 85%</p>
<p id="QandR">Questions Asked Responses Shared Students Joined Posts Featured Questions</p>
</div>
<div id="searchbar-header">
	<p id="s-header">Interested in learning how Packback Questions can support
	<br>
measurable curiosity and improved engagement in your class?</p><br>
<form  action=<%=packback_new_path%> id="s-header-form" method="get">
  <div class="form-inline">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Please Enter your email">
    <button type="submit" id="request-button" class="btn btn-primary">Request a Demo</button>
    </div>
  </form>
<footer class="footer">
	<p>Packback, INC. 601 South LaSalle Street Suite 650, Chicago Illinois, 60605</p>
</footer>
</body>
</html>

app/views/packback/new.html.erb
<!DOCTYPE html>
<html>
<head>

	<title></title>
	<meta charset="UTF-8">


</head>
<body id="demo-body">

	<div class='logo'>  <a href=<%=root_path%>><%= image_tag "Logo.svg",  alt:"Packback Logo"%></a>
	</div>
	 <h1 id="demo-header">Tell us a little bit about your course</h1>
	 <div id="demo-description">
	 <p>To deliever the most helpful and specific demonstration<br> of our
			platform for your specific needs, please tell us a little bit more<br>
			information about you, and your class size and subject.</p>
	 </div>
	<%= form_for :user, :html => {:id => 'demo-forms'} do |f| %>
	<div class='form-group'>
	  <%= f.label :email, 'EMAIL ADDRESS'%><br>
	  <%= f.text_field :email, { class: 'demo-fields'} %><br />

	  <%= f.label :full_name, 'YOUR FULL NAME' %><br>
	  <%= f.text_field :full_name, { class: 'demo-fields'}%><br />

	  <%= f.label :phone_number, 'YOUR PHONE NUMBER' %><br>
	  <%= f.text_field :phone_number, { class: 'demo-fields'} %><br />

	  <%= f.label :course, 'SUBJECT OF YOUR COURSE' %><br>
	  <%= f.text_field :course, { class: 'demo-fields'} %><br />

	  <%= f.label :course_size, 'COURSE SIZE' %><br>
	  <%= f.text_field :course_size, { class: 'demo-fields'}%><br />

	  <%= f.submit 'Save & Request a Demo', :class => 'btn btn-primary'  %>
	  </div>
	<% end %> 
</body>
<footer id="demo-footer">
	<p>Packback, INC. 601 South LaSalle Street Suite 650, Chicago Illinois, 60605</p>
</footer>
</html>